WebApplication1/WebApplication1/Models/Datas.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public partial class Datas
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public DateTime? LastWriteTime { get; set; }
        public string? Path { set; get; }
        public long? Size { get; set; }
    }
}

WebApplication1/WebApplication1/Models/DatasDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    public class DatasDbContext : DbContext
    {
        public DatasDbContext(DbContextOptions<DatasDbContext> options) : base(options)
        {

        }
        public DbSet<Datas> Datas { get; set; }
        //能夠讓建表有特定的狀態        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Datas>().Property(e => e.Id).ValueGeneratedOnAdd();
        }
    }
}

WebApplication1/WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/WebApplication1/Models/Partial/DatasPartial.cs
namespace WebApplication1.Models
{
    public partial class Datas
    {
        public string? FileType { get; set; }
    }
}

WebApplication1/WebApplication1/Models/ViewModel/MyApiViewModel.cs
namespace WebApplication1.Models.ViewModel
{
    public partial class MyApiViewModel
    {
        public string? Name { get; set; }
        public DateTime? LastWriteTime { get; set; }
        public string? Path { set; get; }
    }
}

WebApplication1/WebApplication1/Models/ViewModel/Partial/MyApiViewModelPartial.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.ViewModel
{
    public partial class MyApiViewModel
    {
        [Key]
        public int Id { get; set; }
        public long? Size { get; set; }
        public string? FileType { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/WebApplication1/Controllers/MyApiController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.IO;
using WebApplication1.Models;
using WebApplication1.Models.ViewModel;
using WebApplication1.Service.Interface;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Controllers
{
    public class MyApiController : Controller
    {
        private readonly ILibraryService _libraryService;

        public MyApiController(ILibraryService libraryService)
        {
            this._libraryService = libraryService;
        }
        [HttpGet]
        public IActionResult Get()
        {
            var filePaths = _libraryService.GetFilePaths("Files");
            var fileDbDatas = _libraryService.GetFileDbDatas(filePaths);
            var viewDatas = _libraryService.GetViewDatas(fileDbDatas);

            return View(viewDatas);
        }
        //沒有使用注入服務的_library
        [HttpGet]
        public List<MyApiViewModel> GetInitInformation2()
        {
            var directoryPath = Libs.Library.FolderPath("Files");
            string[] filePaths = Directory.GetFiles(directoryPath);
            var fileDetails = Libs.Library.GetFileDatas(filePaths);

            return fileDetails;
        }
        //使用注入服務的_library
        [HttpGet]
        public List<MyApiViewModel> GetInitInformation()
        {          
            var filePaths = _libraryService.GetFilePaths("Files");
            var fileDatas = _libraryService.GetFileDbDatas(filePaths);
            var viewDatas = _libraryService.GetViewDatas(fileDatas);

            return viewDatas;
        }
        [HttpGet]
        public List<MyApiViewModel> GetInitInformationByService()
        {
            var filePaths = _libraryService.GetFilePaths("Files");
            var fileDatas = _libraryService.GetFileDbDatas(filePaths);
            var viewDatas = _libraryService.GetViewDatas(fileDatas);

            return viewDatas;
        }
        [HttpPost]
        public IActionResult Creat()
        {
            _libraryService.CreateNewTxt();
            var viewData = GetInitInformationByService();

            return Ok(viewData);
        }
        [HttpPost]
        public List<MyApiViewModel> GetOrderBySelection(List<MyApiViewModel> viewModelData, string sortOption)
        {
            var sortedList = _libraryService.GetSortDatas(viewModelData, sortOption);

            return sortedList;
        }
        [HttpPut]
        public IActionResult UpdateData(int viewDataId)
        {
            return Ok(viewDataId);
        }
        [HttpDelete]
        public IActionResult DeleteData(int viewDataId)
        {
            Console.WriteLine("進入刪除controller");
            Console.WriteLine(viewDataId);
            _libraryService.DeleteTxt(viewDataId);


            return Ok(viewDataId);
        }
    }
}

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/WebApplication1/Views/MyApi/Get.cshtml
@model IEnumerable<WebApplication1.Models.ViewModel.MyApiViewModel>

@{
    ViewData["Title"] = "Get";
}
<style>
    .editButton,
    .deleteButton {
        display: inline-block;
        margin-right: 5px;
    }
</style>
<h1>Get</h1>
<label for="sort">排序：</label>
<select id="sort">
    <option value="name1">依名稱(升序)</option>
    <option value="name2">依名稱(降序)</option>
    <option value="time1">依修改時間(升序)</option>
    <option value="time2">依修改時間(降序)</option>
    <option value="path1">依路徑(升序)</option>
    <option value="path2">依路徑(降序)</option>
    <option value="size1">依檔案大小(升序)</option>
    <option value="size2">依檔案大小(降序)</option>
</select>

<button id="btnSubmit">提交</button>

<p><button id="createLink">Create</button></p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastWriteTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastWriteTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileType)
                </td>
                <td>
                    @{
                        if (item.FileType == ".txt")
                        {
                            <button class="editButton" data-id="@item.Id">Edit</button>
                            <button class="deleteButton" data-id="@item.Id">Delete</button>
                        }
                        else
                        {
                            <button class="deleteButton" data-id="@item.Id">Delete</button>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script src="/_framework/aspnetcore-browser-refresh.js"></script>
<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function (e) {
            e.preventDefault();

            var sortValue = $("#sort").val();
            var myApiViewModel = @Html.Raw(Json.Serialize(Model));

            var viewData = {
                sortOption: sortValue,
                viewModelData: myApiViewModel
            };
            $.ajax({
                url: '/MyApi/GetOrderBySelection',
                type: 'POST',
                data: viewData,
                success: function (response) {
                    console.log(response);

                    var tableBody = $(".table tbody");
                    tableBody.empty();

                    response.forEach(function (item) {
                        var row = $("<tr>").append(
                            $("<td>").text(item.name),
                            $("<td>").text(ShowTime(item.lastWriteTime)),
                            $("<td>").text(item.path),
                            $("<td>").text(item.size),
                            $("<td>").text(item.fileType),
                            $("<td>").append(ShowEndCell(item.fileType))
                        )
                        tableBody.append(row);

                        function ShowTime(time) {
                            var recordDateTime = new Date(time);
                            var formattedDateTime = recordDateTime.toLocaleString('en-US', {
                                year: 'numeric',
                                month: 'numeric',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: 'numeric',
                                second: 'numeric',
                                hour12: true
                            });

                            var regex = /(\d+)\/(\d+)\/(\d+), (\d+):(\d+):(\d+) (AM|PM)/;
                            var [, month, day, year, hours, minutes, seconds, amOrPm] = formattedDateTime.match(regex);

                            amOrPm = amOrPm === 'AM' ? '上午' : '下午';
                            var formattedDateTime = `${year}/${month}/${day} ${amOrPm} ${hours}:${minutes}:${seconds}`;

                            return formattedDateTime;
                        }

                        function ShowEndCell(fileType) {
                            if (fileType === '.txt') {
                                var editButton = `<button class="editButton" data-id="${item.id}">Edit</button>`;
                                var deleteButton = `<button class="deleteButton" data-id="${item.id}">Delete</button>`;
                                var separator = ' | ';
                                var endCell = document.createElement('td');

                                endCell.innerHTML = `${editButton} ${separator} ${deleteButton}`;

                                return endCell;
                            } else {
                                var deleteButton = `<button class="deleteButton" data-id="${item.id}">Delete</button>`;
                                var endCell = document.createElement('td');

                                endCell.innerHTML = `${deleteButton}`;

                                return endCell;
                            }
                        }
                    });
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
        //createLink則是一開始就存在HTML內
        $('#createLink').click(function (e) {
            e.preventDefault();
            $.ajax({
                url: '/MyApi/Creat',
                type: 'POST',
                success: function (response) {
                    console.log(response);
                    location.reload();
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });      
    });
    //因ShowEndCell是動態產生的HTML則要在這觸發 
    $(document).on('click','.editButton', function (e) {
        var viewDataId = $(this).data('id');

        $.ajax({
            url: '/MyApi/UpdateData/?viewDataId=' + viewDataId,
            type: 'PUT',
            success: function (response) {
                console.log(response);
                location.reload();
            },
            error: function (xhr, status, error) {
                console.log(error);
            }
        });
    });
    $(document).on('click', '.deleteButton', function (e) {
        var viewDataId = $(this).data('id');

        $.ajax({
            url: '/MyApi/DeleteData/?viewDataId=' + viewDataId,
            type: 'DELETE',
            success: function (response) {
                console.log(response);
                location.reload();
            },
            error: function (xhr, status, error) {
                console.log(error);
            }
        });
    });
</script>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 我的WEB MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyApi" asp-action="Get">MyApi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyApi" asp-action="GetInitInformation2">Json</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyApi" asp-action="GetInitInformationByService">Json(use service)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <div class="text-center">
                <p>
                    <a asp-area="" asp-controller="MyApi" asp-action="Get">MyApi-HomePage</a>
                </p>
                <p>
                    <a asp-area="" asp-controller="MyApi" asp-action="GetInitInformation">MyApi-Json</a>
                </p>       
                <p>
                    <a asp-area="" asp-controller="MyApi" asp-action="GetInitInformationByService">MyApi-Json(use service)</a>
                </p>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>